ProjectCore/Controllers/PrioritiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectCore.DAL.Models;

namespace ProjectCore.Controllers
{
    public class PrioritiesController : Controller
    {
        private readonly ProjectCoreContext _context;

        public PrioritiesController()
        {
            _context = new ProjectCoreContext();
        }

        // GET: Priorities
        public async Task<IActionResult> Index()
        {
            return View(await _context.Priorities.ToListAsync());
        }

        // GET: Priorities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var priorities = await _context.Priorities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (priorities == null)
            {
                return NotFound();
            }

            return View(priorities);
        }

        // GET: Priorities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Priorities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Active")] Priorities priorities)
        {
            if (ModelState.IsValid)
            {
                _context.Add(priorities);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(priorities);
        }

        // GET: Priorities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var priorities = await _context.Priorities.FindAsync(id);
            if (priorities == null)
            {
                return NotFound();
            }
            return View(priorities);
        }

        // POST: Priorities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Active")] Priorities priorities)
        {
            if (id != priorities.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(priorities);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrioritiesExists(priorities.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(priorities);
        }

        // GET: Priorities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var priorities = await _context.Priorities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (priorities == null)
            {
                return NotFound();
            }

            return View(priorities);
        }

        // POST: Priorities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var priorities = await _context.Priorities.FindAsync(id);
            _context.Priorities.Remove(priorities);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PrioritiesExists(int id)
        {
            return _context.Priorities.Any(e => e.Id == id);
        }
    }
}

ProjectCore/Views/Priorities/Create.cshtml
@model ProjectCore.DAL.Models.Priorities

@{
    ViewData["Title"] = "Create";
}

<h2>Create Priorities</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i>
                </button>
                @Html.ActionLink("", "Index", "Priorities", null, new { @class = "btn btn-primary fas fa-undo-alt" })
            </div>
        </form>
    </div>
</div>

ProjectCore/Views/Priorities/Delete.cshtml
@model ProjectCore.DAL.Models.Priorities

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Priorities</h2>

<h3 class="badge badge-danger">Are you sure you want to delete this?</h3>
<div>
    <h4>Priorities</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-primary">
            <i class="fas fa-save"></i>
        </button>
        @Html.ActionLink(" ", "Index", "Priorities", null, new { @class = "btn btn-primary fas fa-undo-alt" })
    </form>
</div>

ProjectCore/Views/Priorities/Details.cshtml
@model ProjectCore.DAL.Models.Priorities

@{
    ViewData["Title"] = "Details";
}

<h2>Details Priorities</h2>

<div>
    <hr />
    <table class="table table-bordered">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Active)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.Active)
            </td>
        </tr>
    </table>
</div>
<div>
    @Html.ActionLink(" ", "Edit", "Priorities", new { id = Model.Id }, new { @class = "btn btn-primary fas fa-edit" })
    @Html.ActionLink(" ", "Index", "Priorities", null, new { @class = "btn btn-primary fas fa-undo-alt" })
</div>

ProjectCore/Views/Priorities/Edit.cshtml
@model ProjectCore.DAL.Models.Priorities

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Priorities</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i>
                </button>
                @Html.ActionLink(" ", "Index", "Priorities", null, new { @class = "btn btn-primary fas fa-undo-alt" })
            </div>
        </form>
    </div>
</div>

ProjectCore/Views/Priorities/Index.cshtml
@model IEnumerable<ProjectCore.DAL.Models.Priorities>

@{
    ViewData["Title"] = "Index";
}

<h2>Priorities</h2>

@Html.ActionLink("", "Create", "Priorities", null, new { @class="btn btn-primary fas fa-plus-circle"})

<hr />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                    @Html.ActionLink("", "Edit", "Priorities", new { id = item.Id }, new { @class = "btn btn-primary fas fa-edit" })
                    @Html.ActionLink("", "Details", "Priorities", new { id = item.Id }, new { @class = "btn btn-primary fas fa-info-circle" })
                    @Html.ActionLink("", "Delete", "Priorities", new { id = item.Id }, new { @class = "btn btn-primary fas fa-trash" })
                </td>
            </tr>
        }
    </tbody>
</table>