ProjectCore/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectCore.DAL.Models;

namespace ProjectCore.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly ProjectCoreContext _context;

        public ActivitiesController()
        {
            _context = new ProjectCoreContext();
        }

        // GET: Activities
        public async Task<IActionResult> Index()
        {
            return View(await _context.Activities.ToListAsync());
        }

        // GET: Activities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activities = await _context.Activities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (activities == null)
            {
                return NotFound();
            }

            return View(activities);
        }

        // GET: Activities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Activities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Active")] Activities activities)
        {
            if (ModelState.IsValid)
            {
                _context.Add(activities);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(activities);
        }

        // GET: Activities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activities = await _context.Activities.FindAsync(id);
            if (activities == null)
            {
                return NotFound();
            }
            return View(activities);
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Active")] Activities activities)
        {
            if (id != activities.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activities);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivitiesExists(activities.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(activities);
        }

        // GET: Activities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activities = await _context.Activities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (activities == null)
            {
                return NotFound();
            }

            return View(activities);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activities = await _context.Activities.FindAsync(id);
            _context.Activities.Remove(activities);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActivitiesExists(int id)
        {
            return _context.Activities.Any(e => e.Id == id);
        }
    }
}

ProjectCore/Views/Activities/Create.cshtml
@model ProjectCore.DAL.Models.Activities

@{
    ViewData["Title"] = "Create";
}

<h2>Create Activites</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i>
                </button>
                @Html.ActionLink("", "Index", "Activities", null, new { @class = "btn btn-primary fas fa-undo-alt" })
            </div>
        </form>
    </div>
</div>

ProjectCore/Views/Activities/Delete.cshtml
@model ProjectCore.DAL.Models.Activities

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Activities</h2>

<h3 class="badge badge-danger">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <table class="table table-bordered">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Active)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.Active)
            </td>
        </tr>
    </table>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-primary">
            <i class="fas fa-save"></i>
        </button>
        @Html.ActionLink(" ", "Index", "Activities", null, new { @class = "btn btn-primary fas fa-undo-alt" })
    </form>
</div>

ProjectCore/Views/Activities/Details.cshtml
@model ProjectCore.DAL.Models.Activities

@{
    ViewData["Title"] = "Details";
}

<h2>Details Activities</h2>

<div>
    <hr />
    <table class="table table-bordered">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Active)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.Active)
            </td>
        </tr>
    </table>
</div>
<div>
    @Html.ActionLink(" ", "Edit", "Activities", new { id=Model.Id}, new { @class = "btn btn-primary fas fa-edit" })
    @Html.ActionLink(" ", "Index", "Activities", null, new { @class = "btn btn-primary fas fa-undo-alt" })

</div>

ProjectCore/Views/Activities/Edit.cshtml
@model ProjectCore.DAL.Models.Activities

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Activities</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i>
                </button>
                @Html.ActionLink(" ", "Index", "Activities", null, new { @class = "btn btn-primary fas fa-undo-alt" })
            </div>
        </form>
    </div>
</div>

ProjectCore/Views/Activities/Index.cshtml
@model IEnumerable<ProjectCore.DAL.Models.Activities>

@{
    ViewData["Title"] = "Index";
}

<h2>Activities</h2>

@Html.ActionLink("", "Create", "Activities", null, new { @class="btn btn-primary fas fa-plus-circle"})

<hr />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.ActionLink("", "Edit", "Activities", new { id = item.Id }, new { @class = "btn btn-primary fas fa-edit" })
                @Html.ActionLink("", "Details", "Activities", new { id = item.Id }, new { @class = "btn btn-primary fas fa-info-circle" })
                @Html.ActionLink("", "Delete", "Activities", new { id = item.Id }, new { @class = "btn btn-primary fas fa-trash" })

            </td>
        </tr>
}
    </tbody>
</table>